## Трогаем датасет

На примере [Popular Sneakers Classification](https://www.kaggle.com/datasets/nikolasgegenava/sneakers-classification?resource=download)

In [1]:
import sys

sys.path.append('..')

%load_ext autoreload
%autoreload 2

In [2]:
from utils.eda_utils import directory_to_dataframe

path_to_dataset = '../archive/sneakers-dataset/sneakers-dataset'
df = directory_to_dataframe(path_to_dataset)
df

                                 path           sneaker_class
0     reebok_classic_leather/0071.jpg  reebok_classic_leather
1     reebok_classic_leather/0065.jpg  reebok_classic_leather
2     reebok_classic_leather/0059.jpg  reebok_classic_leather
3     reebok_classic_leather/0058.jpg  reebok_classic_leather
4     reebok_classic_leather/0064.jpg  reebok_classic_leather
...                               ...                     ...
5948         nike_air_max_97/0083.jpg         nike_air_max_97
5949         nike_air_max_97/0097.jpg         nike_air_max_97
5950         nike_air_max_97/0040.jpg         nike_air_max_97
5951         nike_air_max_97/0054.jpg         nike_air_max_97
5952         nike_air_max_97/0068.jpg         nike_air_max_97

[5953 rows x 2 columns]

In [3]:
df.query('sneaker_class == "yeezy_slide"')

                      path sneaker_class
1796  yeezy_slide/0071.jpg   yeezy_slide
1797  yeezy_slide/0065.jpg   yeezy_slide
1798  yeezy_slide/0059.jpg   yeezy_slide
1799  yeezy_slide/0105.jpg   yeezy_slide
1800  yeezy_slide/0111.jpg   yeezy_slide
...                    ...           ...
1936  yeezy_slide/0083.jpg   yeezy_slide
1937  yeezy_slide/0097.jpg   yeezy_slide
1938  yeezy_slide/0040.jpg   yeezy_slide
1939  yeezy_slide/0054.jpg   yeezy_slide
1940  yeezy_slide/0068.jpg   yeezy_slide

[145 rows x 2 columns]

In [4]:
from utils.eda_utils import sneaker_class_to_brand

class_to_brand = sneaker_class_to_brand(df["sneaker_class"].unique())

df['brand'] = df['sneaker_class'].map(class_to_brand)
df

                                 path           sneaker_class   brand
0     reebok_classic_leather/0071.jpg  reebok_classic_leather  reebok
1     reebok_classic_leather/0065.jpg  reebok_classic_leather  reebok
2     reebok_classic_leather/0059.jpg  reebok_classic_leather  reebok
3     reebok_classic_leather/0058.jpg  reebok_classic_leather  reebok
4     reebok_classic_leather/0064.jpg  reebok_classic_leather  reebok
...                               ...                     ...     ...
5948         nike_air_max_97/0083.jpg         nike_air_max_97    nike
5949         nike_air_max_97/0097.jpg         nike_air_max_97    nike
5950         nike_air_max_97/0040.jpg         nike_air_max_97    nike
5951         nike_air_max_97/0054.jpg         nike_air_max_97    nike
5952         nike_air_max_97/0068.jpg         nike_air_max_97    nike

[5953 rows x 3 columns]

In [5]:
df.groupby('brand').path.count().sort_values(ascending=False)

brand
nike           2295
adidas          950
new_balance     653
converse        544
vans            478
yeezy           401
reebok          246
puma            148
salomon         147
asics            91
Name: path, dtype: int64

In [6]:
from utils.eda_utils import add_image_dimensions

df = add_image_dimensions(df, path_to_dataset)

In [7]:
df['resolution'] = df['width'] * df['height']
df.describe()

             width       height    resolution
count  5953.000000  5953.000000   5953.000000
mean    138.456912   128.475223  17501.932135
std      22.619928    18.591763   2423.368490
min      49.000000    40.000000   6480.000000
25%     117.000000   115.000000  15680.000000
50%     140.000000   140.000000  18306.000000
75%     162.000000   140.000000  19600.000000
max     300.000000   140.000000  22540.000000

In [17]:
from utils.background_analysis import add_background_analysis_to_dataframe

add_background_analysis_to_dataframe(df.sample(10, random_state=42), path_to_dataset)

,path,sneaker_class,brand,width,height,resolution,brightness,color_uniformity,white_ratio,gray_ratio,entropy,color_clusters,uniformity_score,background_type
4040,asics_gel-lyte_iii/0082.jpg,asics_gel-lyte_iii,asics,162,121,19602,254.035197,0.164553,0.997412,0.002588,1.2406,2,0.388184,mixed
4248,new_balance_990/0035.jpg,new_balance_990,new_balance,162,81,13122,78.054622,0.019139,0.004202,0.370588,7.02701,2,0.13131,diverse
1966,adidas_forum_low/0013.jpg,adidas_forum_low,adidas,162,114,18468,236.876261,0.105339,0.984599,0.01487,0.880703,2,0.368269,mixed
4766,vans_sk8-hi/0069.jpg,vans_sk8-hi,vans,112,140,15680,160.970262,0.016932,0.383673,0.366764,7.240702,2,0.25579,diverse
1374,adidas_forum_high/0090.jpg,adidas_forum_high,adidas,162,81,13122,254.919328,0.662787,1.0,0.0,0.393849,2,0.554262,mixed
5193,puma_suede_classic/0133.jpg,puma_suede_classic,puma,90,140,12600,241.169778,0.02542,0.955556,0.016889,3.833713,2,0.332621,mixed
1894,yeezy_slide/0131.jpg,yeezy_slide,yeezy,140,140,19600,143.671997,0.01784,0.211972,0.456745,7.290373,2,0.228852,diverse
3960,asics_gel-lyte_iii/0066.jpg,asics_gel-lyte_iii,asics,140,140,19600,255.0,1.0,1.0,0.0,-0.0,4,0.666667,uniform
4802,new_balance_574/0073.jpg,new_balance_574,new_balance,140,140,19600,241.03239,0.523015,1.0,0.0,0.504995,2,0.507672,mixed
2899,nike_dunk_low/0022.jpg,nike_dunk_low,nike,162,123,19926,254.822199,0.693515,1.0,0.0,0.702163,2,0.564505,mixed

In [26]:
from PIL import Image
import os
with Image.open(os.path.join(path_to_dataset, 'adidas_forum_low/0013.jpg')) as img:
    img.show()