## Fine-tuning эмбеддингов

In [37]:
%load_ext autoreload
%autoreload 3

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [38]:
from torch.optim import Adam
from torch.utils.data import DataLoader



from sneakers_hse.data.utils.s3_tools import S3Client

import polars as pl
import numpy as np
from sklearn.model_selection import train_test_split
from pathlib import Path
import os

In [39]:
PROJECT_ROOT_PATH = Path(os.getenv('PROJECT_ROOT_PATH'))
# # Скачиваю эмбеддинги из s3
# s3 = S3Client(aws_access_key_id=os.getenv("AWS_ACCESS_KEY"),
#               aws_secret_access_key=os.getenv("AWS_SECRET_KEY"))
# s3._download_one(
#     bucket_name='sneakers-hse-images-test',
#     s3_key='dinov2/embeddings.parquet.gzip', # Путь пишем с учётом модели, т.е. каждой модели будет соответстовать отдельный инстанс ChromaDB
#     local_path=str(PROJECT_ROOT_PATH / 'data/04_dinov2_embeddings.parquet.gzip')
# )

In [40]:
df = pl.read_parquet(PROJECT_ROOT_PATH / "data/04_dinov2_embeddings.parquet.gzip")

embeddings = np.stack(df["embedding"].to_list()).astype("float32")
labels = np.array(df["class"].to_list())
paths = df["path"].to_list()
df['class'].value_counts()
train_df_pre = pl.read_csv(PROJECT_ROOT_PATH / 'data/03_yolo_preprocessed/train_images.csv')
test_df = pl.read_csv(PROJECT_ROOT_PATH / 'data/03_yolo_preprocessed/test_images.csv')

train_df, val_df = train_test_split(
    train_df_pre,
    test_size=0.2,
    stratify=train_df_pre["sneaker_class"],
    random_state=42
)

display(train_df.head(), train_df.shape)
display(val_df.head(), val_df.shape)
display(test_df.head(), test_df.shape)
sql = pl.SQLContext()
sql.register_globals()
df = sql.execute(
    '''
select
    df.*
    , case when train_df.path is not null then 'train'
            when val_df.path is not null then 'val'
            when test_df.path is not null then 'test'
            end as sample_part
from df
left join train_df using(path)
left join val_df using(path)
left join test_df using(path)
'''
).collect()
df

shape: (5, 4)
┌───────┬─────────────────────────────────┬─────────────────────────────────┬───────────────┐
│       ┆ path                            ┆ sneaker_class                   ┆ corrupted_flg │
│ ---   ┆ ---                             ┆ ---                             ┆ ---           │
│ i64   ┆ str                             ┆ str                             ┆ i64           │
╞═══════╪═════════════════════════════════╪═════════════════════════════════╪═══════════════╡
│ 2288  ┆ Nike Кеды Dunk Low Retro/cloth… ┆ Nike Кеды Dunk Low Retro        ┆ 0             │
│ 10855 ┆ PUMA Кроссовки Puma Morphic/or… ┆ PUMA Кроссовки Puma Morphic     ┆ 0             │
│ 7477  ┆ Kari Кроссовки/clothing_0_190.… ┆ Kari Кроссовки                  ┆ 0             │
│ 4230  ┆ Reebok Кроссовки CLASSIC LEATH… ┆ Reebok Кроссовки CLASSIC LEATH… ┆ 0             │
│ 2188  ┆ Nike Кеды Dunk Low Retro/cloth… ┆ Nike Кеды Dunk Low Retro        ┆ 0             │
└───────┴─────────────────────────────────┴─────────────────────────────────┴───────────────┘

(8772, 4)

shape: (5, 4)
┌──────┬─────────────────────────────────┬─────────────────────────────────┬───────────────┐
│      ┆ path                            ┆ sneaker_class                   ┆ corrupted_flg │
│ ---  ┆ ---                             ┆ ---                             ┆ ---           │
│ i64  ┆ str                             ┆ str                             ┆ i64           │
╞══════╪═════════════════════════════════╪═════════════════════════════════╪═══════════════╡
│ 7639 ┆ Vans Кеды Knu Skool/clothing_0… ┆ Vans Кеды Knu Skool             ┆ 0             │
│ 2591 ┆ Reebok Кроссовки CLASSIC NYLON… ┆ Reebok Кроссовки CLASSIC NYLON  ┆ 0             │
│ 5027 ┆ Nike Кроссовки AIR MAX 90/clot… ┆ Nike Кроссовки AIR MAX 90       ┆ 0             │
│ 2762 ┆ Under Armour Кроссовки UA CHAR… ┆ Under Armour Кроссовки UA CHAR… ┆ 0             │
│ 240  ┆ Vans Кеды Upland/clothing_0_62… ┆ Vans Кеды Upland                ┆ 0             │
└──────┴─────────────────────────────────┴─────────────────────────────────┴───────────────┘

(2193, 4)

shape: (5, 4)
┌─────┬─────────────────────────────────┬──────────────────┬───────────────┐
│     ┆ path                            ┆ sneaker_class    ┆ corrupted_flg │
│ --- ┆ ---                             ┆ ---              ┆ ---           │
│ i64 ┆ str                             ┆ str              ┆ i64           │
╞═════╪═════════════════════════════════╪══════════════════╪═══════════════╡
│ 14  ┆ Vans Кеды Upland/clothing_0_16… ┆ Vans Кеды Upland ┆ 0             │
│ 32  ┆ Vans Кеды Upland/clothing_0_21… ┆ Vans Кеды Upland ┆ 0             │
│ 44  ┆ Vans Кеды Upland/orig_216_real… ┆ Vans Кеды Upland ┆ 0             │
│ 80  ┆ Vans Кеды Upland/shoe_3_100_re… ┆ Vans Кеды Upland ┆ 0             │
│ 87  ┆ Vans Кеды Upland/clothing_0_27… ┆ Vans Кеды Upland ┆ 0             │
└─────┴─────────────────────────────────┴──────────────────┴───────────────┘

(300, 4)

shape: (11_265, 4)
┌────────────────────────────┬───────────────────────────┬───────────────────────────┬─────────────┐
│ path                       ┆ class                     ┆ embedding                 ┆ sample_part │
│ ---                        ┆ ---                       ┆ ---                       ┆ ---         │
│ str                        ┆ str                       ┆ list[f64]                 ┆ str         │
╞════════════════════════════╪═══════════════════════════╪═══════════════════════════╪═════════════╡
│ Vans Кеды                  ┆ Vans Кеды Upland          ┆ [-1.930393, -0.157552, …  ┆ train       │
│ Upland/clothing_0_26…      ┆                           ┆ 0.300…                    ┆             │
│ Vans Кеды                  ┆ Vans Кеды Upland          ┆ [-1.749115, -1.480964, …  ┆ train       │
│ Upland/clothing_0_57…      ┆                           ┆ -0.96…                    ┆             │
│ Vans Кеды                  ┆ Vans Кеды Upland          ┆ [0.503809, -0.948843, …   ┆ train       │
│ Upland/orig_45.jpeg        ┆                           ┆ -3.250…                   ┆             │
│ Vans Кеды                  ┆ Vans Кеды Upland          ┆ [-1.441995, -2.107342, …  ┆ train       │
│ Upland/clothing_0_0.…      ┆                           ┆ -0.80…                    ┆             │
│ Vans Кеды                  ┆ Vans Кеды Upland          ┆ [-0.845633, -2.200308, …  ┆ train       │
│ Upland/clothing_0_23…      ┆                           ┆ -1.24…                    ┆             │
│ …                          ┆ …                         ┆ …                         ┆ …           │
│ Under Armour Кроссовки UA  ┆ Under Armour Кроссовки UA ┆ [0.131167, -0.318168, …   ┆ train       │
│ Phan…                      ┆ Phan…                     ┆ -0.669…                   ┆             │
│ Under Armour Кроссовки UA  ┆ Under Armour Кроссовки UA ┆ [1.267569, -3.275375, …   ┆ train       │
│ Phan…                      ┆ Phan…                     ┆ -2.853…                   ┆             │
│ Under Armour Кроссовки UA  ┆ Under Armour Кроссовки UA ┆ [1.495174, -1.613851, …   ┆ train       │
│ Phan…                      ┆ Phan…                     ┆ -1.374…                   ┆             │
│ Under Armour Кроссовки UA  ┆ Under Armour Кроссовки UA ┆ [0.911693, -2.18018, …    ┆ train       │
│ Phan…                      ┆ Phan…                     ┆ -2.3576…                  ┆             │
│ Under Armour Кроссовки UA  ┆ Under Armour Кроссовки UA ┆ [-2.148961, -1.149063, …  ┆ val         │
│ Phan…                      ┆ Phan…                     ┆ 2.430…                    ┆             │
└────────────────────────────┴───────────────────────────┴───────────────────────────┴─────────────┘

In [41]:
train_df = df.filter(pl.col('sample_part') == 'train')
val_df = df.filter(pl.col('sample_part') == 'val')
test_df = df.filter(pl.col('sample_part') == 'test')
train_df

shape: (8_772, 4)
┌────────────────────────────┬───────────────────────────┬───────────────────────────┬─────────────┐
│ path                       ┆ class                     ┆ embedding                 ┆ sample_part │
│ ---                        ┆ ---                       ┆ ---                       ┆ ---         │
│ str                        ┆ str                       ┆ list[f64]                 ┆ str         │
╞════════════════════════════╪═══════════════════════════╪═══════════════════════════╪═════════════╡
│ Vans Кеды                  ┆ Vans Кеды Upland          ┆ [-1.930393, -0.157552, …  ┆ train       │
│ Upland/clothing_0_26…      ┆                           ┆ 0.300…                    ┆             │
│ Vans Кеды                  ┆ Vans Кеды Upland          ┆ [-1.749115, -1.480964, …  ┆ train       │
│ Upland/clothing_0_57…      ┆                           ┆ -0.96…                    ┆             │
│ Vans Кеды                  ┆ Vans Кеды Upland          ┆ [0.503809, -0.948843, …   ┆ train       │
│ Upland/orig_45.jpeg        ┆                           ┆ -3.250…                   ┆             │
│ Vans Кеды                  ┆ Vans Кеды Upland          ┆ [-1.441995, -2.107342, …  ┆ train       │
│ Upland/clothing_0_0.…      ┆                           ┆ -0.80…                    ┆             │
│ Vans Кеды                  ┆ Vans Кеды Upland          ┆ [-0.845633, -2.200308, …  ┆ train       │
│ Upland/clothing_0_23…      ┆                           ┆ -1.24…                    ┆             │
│ …                          ┆ …                         ┆ …                         ┆ …           │
│ Under Armour Кроссовки UA  ┆ Under Armour Кроссовки UA ┆ [-1.853474, -1.394531, …  ┆ train       │
│ Phan…                      ┆ Phan…                     ┆ -1.65…                    ┆             │
│ Under Armour Кроссовки UA  ┆ Under Armour Кроссовки UA ┆ [0.131167, -0.318168, …   ┆ train       │
│ Phan…                      ┆ Phan…                     ┆ -0.669…                   ┆             │
│ Under Armour Кроссовки UA  ┆ Under Armour Кроссовки UA ┆ [1.267569, -3.275375, …   ┆ train       │
│ Phan…                      ┆ Phan…                     ┆ -2.853…                   ┆             │
│ Under Armour Кроссовки UA  ┆ Under Armour Кроссовки UA ┆ [1.495174, -1.613851, …   ┆ train       │
│ Phan…                      ┆ Phan…                     ┆ -1.374…                   ┆             │
│ Under Armour Кроссовки UA  ┆ Under Armour Кроссовки UA ┆ [0.911693, -2.18018, …    ┆ train       │
│ Phan…                      ┆ Phan…                     ┆ -2.3576…                  ┆             │
└────────────────────────────┴───────────────────────────┴───────────────────────────┴─────────────┘

## Обучаю модель

In [69]:
from sneakers_hse.model.triplet_loss import EmbeddingDataset
from pytorch_metric_learning.samplers import MPerClassSampler

train_dataset = EmbeddingDataset(train_df)
sampler = MPerClassSampler(labels=train_dataset.labels, m=4, batch_size=64, length_before_new_iter=1_000)
train_dataloader = DataLoader(train_dataset, sampler=sampler)

val_dataset = EmbeddingDataset(val_df)
val_dataloader = DataLoader(val_dataset, batch_size=64)

In [70]:
for x, y in train_dataloader:
    print(x.shape)
    break

torch.Size([1, 768])

In [71]:
from pytorch_metric_learning import losses, miners

loss_fn = losses.TripletMarginLoss(margin=0.2)

miner = miners.TripletMarginMiner(
    margin=0.2,
    type_of_triplets="semihard"
)

In [72]:
import torch.nn as nn

input_dim = 768
embedding_dim = 768
model = nn.Sequential(
    nn.Linear(input_dim, 1024),
    nn.ReLU(),
    nn.Linear(1024, 1024),
    nn.ReLU(),
    nn.Linear(1024, embedding_dim)
)
model = model.train()
model

Sequential(
  (0): Linear(in_features=768, out_features=1024, bias=True)
  (1): ReLU()
  (2): Linear(in_features=1024, out_features=1024, bias=True)
  (3): ReLU()
  (4): Linear(in_features=1024, out_features=768, bias=True)
)

In [73]:
import torch

val_df

shape: (2_193, 5)
┌──────────────────────┬──────────────────────┬────────────────┬─────────────┬─────────────────────┐
│ path                 ┆ class                ┆ embedding      ┆ sample_part ┆ new_embedding       │
│ ---                  ┆ ---                  ┆ ---            ┆ ---         ┆ ---                 │
│ str                  ┆ str                  ┆ list[f64]      ┆ str         ┆ array[f32, 768]     │
╞══════════════════════╪══════════════════════╪════════════════╪═════════════╪═════════════════════╡
│ Vans Кеды            ┆ Vans Кеды Upland     ┆ [-1.147287,    ┆ val         ┆ [-0.146398,         │
│ Upland/orig_28.jpeg  ┆                      ┆ -1.009799, …   ┆             ┆ -0.042614, … -0.24… │
│                      ┆                      ┆ 0.806…         ┆             ┆                     │
│ Vans Кеды Upland/clo ┆ Vans Кеды Upland     ┆ [-1.412233,    ┆ val         ┆ [-0.282348,         │
│ thing_0_94…          ┆                      ┆ -1.431905, …   ┆             ┆ 0.055301, … -0.280… │
│                      ┆                      ┆ -0.19…         ┆             ┆                     │
│ Vans Кеды            ┆ Vans Кеды Upland     ┆ [-0.926339,    ┆ val         ┆ [-0.144878,         │
│ Upland/orig_115.jpeg ┆                      ┆ 0.773644, …    ┆             ┆ -0.039798, … -0.33… │
│                      ┆                      ┆ -0.431…        ┆             ┆                     │
│ Vans Кеды Upland/clo ┆ Vans Кеды Upland     ┆ [-1.072493,    ┆ val         ┆ [-0.273616,         │
│ thing_0_19…          ┆                      ┆ -4.571333, …   ┆             ┆ 0.018096, … -0.343… │
│                      ┆                      ┆ -0.35…         ┆             ┆                     │
│ Vans Кеды Upland/clo ┆ Vans Кеды Upland     ┆ [-1.447895,    ┆ val         ┆ [-0.248794,         │
│ thing_0_61…          ┆                      ┆ -0.958692, …   ┆             ┆ 0.080571, … -0.309… │
│                      ┆                      ┆ -0.99…         ┆             ┆                     │
│ …                    ┆ …                    ┆ …              ┆ …           ┆ …                   │
│ Under Armour         ┆ Under Armour         ┆ [1.329301,     ┆ val         ┆ [-0.156632,         │
│ Кроссовки UA Phan…   ┆ Кроссовки UA Phan…   ┆ -1.360057, …   ┆             ┆ -0.019594, … -0.18… │
│                      ┆                      ┆ -1.224…        ┆             ┆                     │
│ Under Armour         ┆ Under Armour         ┆ [-0.504423,    ┆ val         ┆ [-0.133833,         │
│ Кроссовки UA Phan…   ┆ Кроссовки UA Phan…   ┆ -1.179003, …   ┆             ┆ 0.014703, … -0.202… │
│                      ┆                      ┆ -0.58…         ┆             ┆                     │
│ Under Armour         ┆ Under Armour         ┆ [-0.133964,    ┆ val         ┆ [0.071868,          │
│ Кроссовки UA Phan…   ┆ Кроссовки UA Phan…   ┆ 0.777298, …    ┆             ┆ -0.067333, …        │
│                      ┆                      ┆ -0.496…        ┆             ┆ -0.311…             │
│ Under Armour         ┆ Under Armour         ┆ [-0.304712,    ┆ val         ┆ [-0.233781,         │
│ Кроссовки UA Phan…   ┆ Кроссовки UA Phan…   ┆ -2.066366, …   ┆             ┆ -0.092626, … -0.37… │
│                      ┆                      ┆ -0.03…         ┆             ┆                     │
│ Under Armour         ┆ Under Armour         ┆ [-2.148961,    ┆ val         ┆ [-0.19639,          │
│ Кроссовки UA Phan…   ┆ Кроссовки UA Phan…   ┆ -1.149063, …   ┆             ┆ -0.041241, …        │
│                      ┆                      ┆ 2.430…         ┆             ┆ -0.175…             │
└──────────────────────┴──────────────────────┴────────────────┴─────────────┴─────────────────────┘

In [86]:
from tqdm import tqdm
import chromadb
from sneakers_hse.metrics import get_neighbors
from torch.optim import Adam

device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)
optimizer = Adam(model.parameters(), lr=1e-3)

num_epochs = 10


client = chromadb.Client()
for epoch in range(num_epochs):

    # Train
    model.train()
    total_loss = 0
    for embeddings, labels in tqdm(train_dataloader):
        
        embeddings = embeddings.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        projected = model(embeddings)

        hard_pairs = miner(projected, labels)
        loss = loss_fn(projected, labels, hard_pairs)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()
    print(f"Epoch {epoch}: loss={total_loss:.4f}")

    # Val
    model.eval()
    collection = client.get_or_create_collection(
            "new_embeddings",
            metadata={"hnsw:space": "cosine"}
        )
    new_embeddings = []
    for embedding, labels in val_dataloader:
        with torch.no_grad():
            new_embedding = model(embedding)
        new_embeddings.append(new_embedding)
    new_embeddings = torch.concat(new_embeddings).numpy()

    val_df = val_df.with_columns(new_embedding = new_embeddings)
    collection.add(val_df['path'].to_list(),
                   embeddings=new_embeddings,
                   metadatas=[{"class": c} for c in val_df['class'].to_list()])
    neighbors = get_neighbors(collection, new_embeddings)
    val_df = val_df.with_columns(neighbors=neighbors)
    val_df = val_df.with_columns(
        pl.struct(["neighbors", "class"]).map_elements(
            lambda row: [
                1 if n == row["class"] else 0
                for n in row["neighbors"]
            ]
        ).alias("hit_flg")
    )
    for k in [1, 5, 10]:
        print(f"\nMetrics @ {k}")
        df_k = df.with_columns(hits_k = pl.col("hit_flg").list.slice(0, k))\
            .with_columns(
                pos = pl.int_ranges(1, pl.col("hits_k").list.len() + 1),
                hit_at_k = pl.col("hits_k").list.max(),
                precision_at_k = pl.col("hits_k").list.mean()
            )
        display(df_k.select(
            pl.col('hit_at_k').mean(),
            pl.col('precision_at_k').mean()
        ))
    client.delete_collection('new_embeddings')

100%|██████████| 960/960 [00:03<00:00, 263.37it/s]

Epoch 0: loss=0.0000
{'ids': [['Vans Кеды Upland/orig_28.jpeg', 'Vans Кеды Upland/orig_276.jpeg', 'Vans Кеды Upland/orig_133.jpeg', 'Reebok Кроссовки CLASSIC NYLON/orig_76.jpeg', 'Vans Кеды Upland/orig_36.jpeg', 'Vans Кеды Upland/orig_214.jpeg', 'PUMA Кроссовки Hypnotic LS/orig_42.jpeg', 'Vans Кеды Upland/clothing_0_163.jpeg', 'adidas Кроссовки DROPSET 3 TRAINER/orig_94.jpeg', 'X-Plode Кеды/orig_5.jpeg', 'adidas Кроссовки RUNFALCON 5/orig_109.jpeg'], ['Vans Кеды Upland/clothing_0_94.jpeg', 'Reebok Кроссовки CLASSIC LEATHER/orig_192.jpeg', 'Vans Кеды Upland/clothing_0_125.jpeg', 'Vans Кеды Upland/clothing_0_167.jpeg', 'PUMA Кроссовки Hypnotic LS/clothing_0_124.jpeg', 'Vans Кеды Upland/clothing_0_254.jpeg', 'Under Armour Кроссовки UA CHARGED EDGE/clothing_0_75.jpeg', 'Under Armour Кроссовки UA CHARGED EDGE/clothing_0_113.jpeg', 'Vans Кеды Upland/orig_27.jpeg', 'Vans Кеды Upland/clothing_0_148.jpeg', 'Nike Кеды Dunk Low Retro/orig_283.jpeg'], ['Vans Кеды Upland/orig_115.jpeg', 'Vans Кеды Upland/orig_220.jpeg', 'PUMA Кеды CA Pro Classic II/orig_137.jpeg', 'Nike Кроссовки AIR PEGASUS 2005/orig_242.jpeg', 'Vans Кеды Hylane/clothing_0_213.jpeg', 'Reebok Кеды CLUB C 85/orig_282.jpeg', 'Reebok Кроссовки CLASSIC NYLON/orig_271.jpeg', 'Nike Кеды FIELD GENERAL/orig_69.jpeg', 'Nike Кроссовки AIR MAX 90/orig_286.jpeg', 'Nike Кеды Dunk Low Retro/orig_56.jpeg', 'Nike Кеды FIELD GENERAL/orig_238.jpeg'], ['Vans Кеды Upland/clothing_0_194.jpeg', 'Vans Кеды Upland/clothing_0_179.jpeg', 'Under Armour Кроссовки UA CHARGED EDGE/clothing_0_287.jpeg', 'X-Plode Кеды/clothing_0_128.jpeg', 'X-Plode Кеды/clothing_0_267.jpeg', 'Nike Кеды NIKE AIR FORCE 1/clothing_0_110.jpeg', 'adidas Кроссовки DURAMO SL2 M/clothing_0_27.jpeg', 'Nike Кеды FIELD GENERAL/clothing_0_28.jpeg', 'adidas Кроссовки RUNFALCON 5/clothing_0_286.jpeg', 'X-Plode Кеды/clothing_0_199.jpeg', 'X-Plode Кеды/clothing_0_253.jpeg'], ['Vans Кеды Upland/clothing_0_61.jpeg', 'Vans Кеды Upland/clothing_0_93.jpeg', 'Vans Кеды Upland/clothing_0_158.jpeg', 'Nike Кроссовки AIR MAX 90/clothing_0_86.jpeg', 'Vans Кеды Upland/clothing_0_213.jpeg', 'PUMA Кроссовки RS-X Efekt PRM/clothing_0_34.jpeg', 'Reebok Кроссовки CLASSIC LEATHER/clothing_0_287.jpeg', 'Vans Кеды Hylane/clothing_0_245.jpeg', 'X-Plode Кроссовки/clothing_0_250.jpeg', 'Vans Кеды Upland/clothing_0_129.jpeg', 'Reebok Кеды CLUB C 85/clothing_0_124.jpeg'], ['Vans Кеды Upland/clothing_0_98.jpeg', 'Vans Кеды Upland/clothing_0_65.jpeg', 'Vans Кеды Upland/clothing_0_62.jpeg', 'Vans Кеды Upland/clothing_0_218.jpeg', 'Vans Кеды Upland/clothing_0_51.jpeg', 'Reebok Кеды CLUB C GROUNDS UK/clothing_0_153.jpeg', 'Vans Кеды Hylane/clothing_0_265.jpeg', 'Reebok Кеды CLUB C GROUNDS UK/clothing_0_144.jpeg', 'adidas Кроссовки DURAMO SL2 M/clothing_0_464.jpeg', 'Reebok Кеды CLUB C GROUNDS UK/clothing_0_236.jpeg', 'Nike Кеды NIKE AIR FORCE 1/clothing_0_80.jpeg'], ['Vans Кеды Upland/clothing_0_244.jpeg', 'Vans Кеды Hylane/clothing_0_219.jpeg', 'Vans Кеды Hylane/clothing_0_179.jpeg', 'Vans Кеды Hylane/clothing_0_25.jpeg', 'Vans Кеды Hylane/clothing_0_186.jpeg', 'Vans Кеды Hylane/clothing_0_71.jpeg', 'Vans Кеды Hylane/clothing_0_227.jpeg', 'Vans Кеды Upland/clothing_0_189.jpeg', 'PUMA Кеды CA Pro Classic II/clothing_0_123.jpeg', 'Vans Кеды Upland/clothing_0_112.jpeg', 'PUMA Кроссовки Hypnotic LS/clothing_0_105.jpeg'], ['Vans Кеды Upland/clothing_0_213.jpeg', 'Vans Кеды Upland/clothing_0_170.jpeg', 'Vans Кеды Upland/clothing_0_61.jpeg', 'Reebok Кроссовки CLASSIC NYLON/clothing_0_234.jpeg', 'Reebok Кроссовки CLASSIC LEATHER/clothing_0_159.jpeg', 'Vans Кеды Upland/clothing_0_93.jpeg', 'Reebok Кеды CLUB C GROUNDS UK/clothing_0_99.jpeg', 'Vans Кеды Upland/clothing_0_158.jpeg', 'X-Plode Кроссовки/clothing_0_250.jpeg', 'Reebok Кроссовки CLASSIC LEATHER/clothing_0_104.jpeg', 'Kari Кеды/clothing_0_160.jpeg'], ['Vans Кеды Upland/clothing_0_183.jpeg', 'Vans Кеды Hylane/clothing_0_164.jpeg', 'Vans Кеды Upland/orig_195.jpeg', 'Under Armour Кроссовки UA Phantom 4/clothing_0_210.jpeg', 'Vans Кеды Old Skool/clothing_0_30.jpeg', 'Reebok Кроссовки CLASSIC NYLON/orig_224.jpeg', 'adidas Кроссовки adizero Evo SL M/clothing_0_18.jpeg', 'PUMA Кеды CA Pro Classic II/clothing_0_115.jpeg', 'PUMA Кеды CA Pro Classic II/clothing_0_88.jpeg', 'Under Armour Кроссовки UA Charged Surge 4/clothing_0_284.jpeg', 'adidas Кроссовки DURAMO SL2 M/clothing_0_469.jpeg'], ['Vans Кеды Upland/clothing_0_137.jpeg', 'Vans Кеды Upland/clothing_0_112.jpeg', 'Vans Кеды Upland/clothing_0_125.jpeg', 'Vans Кеды Upland/clothing_0_11.jpeg', 'Vans Кеды Hylane/clothing_0_219.jpeg', 'Reebok Кроссовки CLASSIC LEATHER/clothing_0_131.jpeg', 'Vans Кеды Upland/clothing_0_254.jpeg', 'Vans Кеды Upland/clothing_0_121.jpeg', 'Vans Кеды Upland/clothing_0_244.jpeg', 'PUMA Кеды CA Pro Classic II/clothing_0_123.jpeg', 'Vans Кеды Upland/clothing_0_189.jpeg']], 'embeddings': None, 'documents': [[None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None]], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None, None, None]], 'distances': [[1.7881393432617188e-07, 0.07329636812210083, 0.08753633499145508, 0.09022891521453857, 0.09083890914916992, 0.09974038600921631, 0.1041141152381897, 0.10517805814743042, 0.10690224170684814, 0.10704028606414795, 0.10912227630615234], [3.5762786865234375e-07, 0.05837744474411011, 0.07097727060317993, 0.07215821743011475, 0.07422047853469849, 0.07627105712890625, 0.07824742794036865, 0.07849979400634766, 0.07872360944747925, 0.08203846216201782, 0.08455538749694824], [-2.384185791015625e-07, 0.0632404088973999, 0.12987619638442993, 0.1433326005935669, 0.1497875452041626, 0.1561480164527893, 0.15709000825881958, 0.16239452362060547, 0.1642022728919983, 0.16471099853515625, 0.16565567255020142], [4.76837158203125e-07, 0.083152174949646, 0.11212193965911865, 0.12365603446960449, 0.1258995532989502, 0.12682002782821655, 0.1301557421684265, 0.13510435819625854, 0.13711762428283691, 0.13777101039886475, 0.13805854320526123], [-5.960464477539062e-07, 0.05647212266921997, 0.06426781415939331, 0.06738072633743286, 0.06933093070983887, 0.08245730400085449, 0.08637619018554688, 0.0883321762084961, 0.08855348825454712, 0.08867156505584717, 0.08941096067428589], [1.1920928955078125e-07, 0.06060898303985596, 0.06421834230422974, 0.064236581325531, 0.06575238704681396, 0.07836055755615234, 0.07874888181686401, 0.08540076017379761, 0.08560800552368164, 0.08790040016174316, 0.08948308229446411], [7.152557373046875e-07, 0.04032564163208008, 0.04448246955871582, 0.053942978382110596, 0.05601400136947632, 0.056764304637908936, 0.05804818868637085, 0.06118494272232056, 0.06149357557296753, 0.0673477053642273, 0.06973773241043091], [-3.5762786865234375e-07, 0.04814350605010986, 0.06933128833770752, 0.0697970986366272, 0.06983160972595215, 0.07681316137313843, 0.08245736360549927, 0.08655822277069092, 0.08967983722686768, 0.098030686378479, 0.09875845909118652], [-7.152557373046875e-07, 0.09841173887252808, 0.1065937876701355, 0.12542229890823364, 0.12786716222763062, 0.13000088930130005, 0.13073831796646118, 0.13080406188964844, 0.13281816244125366, 0.13576358556747437, 0.1359063982963562], [4.172325134277344e-07, 0.029798448085784912, 0.04214745759963989, 0.05060780048370361, 0.05631977319717407, 0.06264626979827881, 0.06403917074203491, 0.06428951025009155, 0.07222509384155273, 0.07281804084777832, 0.07529908418655396]]}

TypeError: 'NoneType' object is not subscriptable

In [76]:
collection.get('Vans Кеды Upland/orig_28.jpeg', include=['embeddings'])

{'ids': ['Vans Кеды Upland/orig_28.jpeg'],
 'embeddings': array([[-1.47078365e-01,  2.57406294e-01,  2.37518698e-01,
          1.37765789e-02, -1.15086406e-01, -3.29904079e-01,
         -1.36756375e-01, -3.09500452e-02,  2.58732378e-01,
          3.86957228e-02,  1.57681659e-01,  5.14240026e-01,
          1.40181437e-01, -2.82009572e-01,  1.39537454e-01,
         -2.67069399e-01, -2.57970840e-01,  3.41405123e-01,
          9.87437293e-02, -1.09773658e-01,  1.60057038e-01,
         -1.82513207e-01,  2.22383648e-01,  2.28469595e-01,
          2.11753979e-01, -1.14118271e-01,  4.72986256e-04,
         -5.81337139e-02, -1.68772608e-01,  1.84595495e-01,
          5.28222285e-02, -3.48801166e-01,  2.42122501e-01,
         -9.92079526e-02,  1.55692726e-01, -4.76329923e-02,
         -6.33245334e-02, -1.10706411e-01,  2.04372749e-01,
          3.26428446e-03, -1.96937442e-01,  5.05853295e-02,
         -6.44004270e-02, -1.75388217e-01,  8.60712752e-02,
          3.29416478e-03, -2.13989303e-01,  1.27937511e-01,
         -3.03179305e-02, -2.93097645e-02,  2.56953061e-01,
          6.95140287e-02,  1.77475885e-01,  3.51851359e-02,
         -1.48973286e-01,  5.64732626e-02,  1.01413101e-01,
         -2.13631615e-01,  1.36471272e-01, -2.14024007e-01,
         -7.15818107e-02, -6.90374300e-02, -2.13210769e-02,
         -8.68333355e-02, -5.78428656e-02,  9.92236286e-02,
          1.08514644e-01, -1.50925979e-01,  3.01335603e-01,
          3.00436139e-01, -3.36587727e-01,  1.16058379e-01,
          1.89969286e-01,  2.16934949e-01, -2.86064059e-01,
          2.34837934e-01,  1.40525624e-01, -4.39768806e-02,
         -1.35998130e-01, -6.80783391e-02, -3.20639461e-02,
         -3.37963700e-02, -5.66987740e-03, -1.24601156e-01,
         -1.40996516e-01,  1.44940898e-01,  2.70478167e-02,
         -1.61464363e-01,  2.90577877e-02, -4.98959795e-02,
         -6.32972345e-02, -5.94054274e-02,  2.36417830e-01,
         -5.64055424e-03, -6.73316047e-02, -1.39944151e-01,
         -1.13696277e-01,  3.04641370e-02, -2.06341371e-01,
         -8.12559202e-02, -1.06095679e-01,  1.40912041e-01,
          8.22655559e-02, -9.48844943e-03, -2.85243481e-01,
         -6.07159883e-02,  1.34501100e-01, -1.58607230e-01,
         -9.98585075e-02, -2.81954199e-01, -7.64157474e-02,
          2.78231055e-01,  4.33048010e-02,  1.28376678e-01,
          1.35234177e-01,  2.15275377e-01,  1.09570630e-01,
         -1.02139704e-01,  3.16980854e-02,  9.26298425e-02,
         -1.74834281e-01, -2.18600836e-02, -2.13465080e-01,
         -1.72701746e-01, -1.13814764e-01,  5.29753007e-02,
          1.23881418e-02, -1.42661452e-01, -1.06509954e-01,
         -1.22968584e-01,  1.27047896e-01, -4.40098196e-02,
         -2.85014440e-03,  2.05048516e-01,  4.16063011e-01,
          2.33190104e-01, -1.43195033e-01, -1.84610188e-01,
         -5.75337261e-02,  1.71204116e-02,  3.35447080e-02,
          1.15203999e-01,  3.87165658e-02, -6.80441186e-02,
         -1.50992796e-01,  1.60594285e-01,  2.50593014e-02,
          8.33222270e-02, -2.04252079e-01, -1.97583586e-02,
          7.75613785e-02, -4.23711061e-01,  4.18956690e-02,
         -1.32234663e-01,  4.81522642e-03,  3.68151478e-02,
         -5.52965887e-02,  2.29213953e-01, -9.41275582e-02,
          3.54366638e-02,  2.62286186e-01,  4.94878404e-02,
          5.63655049e-02,  1.10606812e-01, -3.94467264e-01,
         -7.42607564e-02, -5.36170080e-02, -7.91767053e-03,
          6.77855462e-02,  1.58609256e-01, -1.63161685e-03,
          1.67356431e-01,  1.61060318e-02,  9.26668718e-02,
         -8.93004015e-02, -2.96576083e-01,  1.79214105e-01,
          3.02989800e-02,  2.90248662e-01,  1.72973320e-01,
          4.23570946e-02, -7.92635828e-02,  3.62849608e-02,
          2.27700114e-01, -3.97657633e-01,  5.92177995e-02,
         -4.46497602e-03, -5.93954884e-02,  6.63729161e-02,
         -2.42138267e-01, -3.54803242e-02, -2.89705358e-02,
          3.02415192e-01,  3.60429436e-02,  1.21870719e-01,
         -9.67794061e-02,  2.57938653e-01, -1.83421239e-01,
          5.77481687e-02, -2.40889072e-01,  1.92105696e-01,
          8.09827726e-03, -1.17171362e-01, -4.86878902e-02,
          2.61824415e-03, -2.84468263e-01, -1.91286635e-02,
         -1.50217995e-01,  2.05984488e-01,  1.21748291e-01,
          2.66646713e-01,  5.51551729e-02, -3.53129804e-02,
          1.52182475e-01,  7.45806992e-02,  2.70303227e-02,
          1.72093168e-01,  1.34343237e-01,  1.34644583e-01,
          3.77098978e-01,  1.50697723e-01, -1.23417757e-01,
         -3.24847877e-01,  8.55673552e-02,  1.64693911e-02,
         -1.01161130e-01,  1.35834608e-02,  2.90842324e-01,
         -3.07906032e-01,  1.77254140e-01, -6.71290904e-02,
          1.66262567e-01,  1.46345183e-01,  1.66011363e-01,
          2.27983057e-01, -3.25823203e-02, -1.34667426e-01,
          6.51370734e-02,  4.87088738e-03,  2.08679843e-03,
          2.15207458e-01, -1.50613841e-02,  4.36147302e-02,
          9.25073624e-02, -9.77393910e-02, -4.37222458e-02,
          7.87186921e-02,  2.42124781e-01,  4.07487825e-02,
          1.71757206e-01,  1.81016505e-01, -1.77846909e-01,
          1.46575153e-01,  2.16999035e-02,  1.41318198e-02,
         -4.96111102e-02,  5.14968857e-02, -1.30099416e-01,
          3.74483883e-01, -5.64083904e-02, -5.30633777e-02,
         -2.35663101e-01,  2.61288434e-01,  1.93156168e-01,
         -1.44100249e-01,  1.56647921e-01, -7.41022527e-02,
         -1.92190319e-01,  2.28030115e-01,  1.58403233e-01,
          3.16722617e-02,  2.60493755e-01, -6.93443939e-02,
          8.61500725e-02, -5.80313765e-02,  1.32274717e-01,
          8.79963860e-02,  1.07607774e-01,  1.75047725e-01,
         -3.16314548e-02, -1.08432025e-03, -4.30618227e-02,
          3.43584716e-01, -9.95686799e-02,  8.80818516e-02,
          1.33158177e-01,  3.58619541e-02, -1.67600870e-01,
         -1.51595995e-01, -8.88494626e-02, -8.80342349e-03,
          5.77382557e-02,  1.20302938e-01, -8.48371070e-03,
         -9.28236288e-04,  1.55216798e-01,  2.49440670e-02,
         -3.72534275e-01, -3.32128033e-02, -1.53941974e-01,
         -6.12438768e-02, -1.84566528e-01,  1.02068491e-01,
          1.29617229e-01,  5.72068198e-03,  7.37982541e-02,
         -2.18655378e-01,  9.67912227e-02,  1.24416642e-01,
         -1.38121679e-01,  3.71187866e-01,  2.06445977e-02,
         -1.39577299e-01, -4.72212099e-02, -1.84262380e-01,
         -2.17562303e-01,  1.35931939e-01,  1.44784674e-01,
          1.57192409e-01,  1.67248189e-01, -1.13226198e-01,
          7.17681274e-02,  1.07635960e-01,  3.89978811e-02,
         -2.50772923e-01,  6.87544839e-03, -1.05201326e-01,
          5.99014238e-02,  1.85873538e-01, -2.82253474e-01,
         -2.30766416e-01, -5.95751703e-02, -1.39324954e-02,
          5.53331710e-02, -2.72322446e-01,  2.79028807e-02,
          1.28574759e-01, -7.00596422e-02,  1.38977557e-01,
         -1.03738286e-01, -1.19762952e-02,  9.33537111e-02,
         -1.62815168e-01,  3.78173850e-02, -4.65416070e-03,
         -1.33686304e-01,  7.28509203e-02, -5.09348814e-04,
         -3.41179520e-02,  6.75670952e-02, -1.12443984e-01,
         -9.74931270e-02, -1.11853793e-01, -4.07027602e-02,
          2.45755669e-02, -8.36775377e-02, -8.77879560e-02,
         -4.36050817e-02, -3.42278779e-01,  1.04250804e-01,
          5.63121913e-03, -3.11243311e-02,  4.17611562e-02,
         -1.41142249e-01,  1.88795641e-01, -4.57548559e-01,
         -1.74528509e-01, -6.15865774e-02, -4.88397665e-02,
         -4.37287576e-02, -9.49487323e-04,  1.71199009e-01,
         -3.03011965e-02, -1.79626331e-01,  5.56610003e-02,
          2.53058612e-01, -6.15398623e-02,  1.01171084e-01,
         -2.47950982e-02, -3.59135047e-02,  3.74680907e-01,
         -1.45372599e-01, -1.07194677e-01, -3.44920680e-02,
          5.68285547e-02,  2.56065398e-01, -7.81453848e-02,
         -1.95110351e-01, -1.68575123e-01,  1.33855283e-01,
          1.52022809e-01, -4.12841477e-02, -1.60254743e-02,
          4.93717045e-02, -4.93085012e-02,  3.62374872e-01,
          3.79157402e-02,  1.09772965e-01, -2.59809822e-01,
          8.42966735e-02, -1.14084870e-01, -3.92897746e-05,
         -5.45747094e-02,  1.68248326e-01, -5.31384815e-03,
         -4.41028439e-02,  9.10239518e-02, -6.71432540e-02,
          1.49226561e-01, -1.24870062e-01, -3.01029354e-01,
         -2.75330067e-01, -8.88381898e-02, -8.69978070e-02,
          9.66466963e-02,  9.42672491e-02, -3.77065577e-02,
         -1.42367873e-02, -6.60730749e-02,  1.47557095e-01,
         -1.88310772e-01, -5.13379648e-03,  8.91039521e-02,
         -7.87188858e-02, -3.45292278e-02,  1.00550592e-01,
         -6.91720797e-03, -3.49231772e-02,  1.10086560e-01,
         -9.02524684e-03,  2.03879476e-02,  2.06408538e-02,
         -1.89456910e-01, -4.92456332e-02, -1.04279391e-01,
          1.35684386e-01, -3.57621089e-02,  3.10139526e-02,
          1.25264511e-01, -3.09304148e-01,  6.20111590e-03,
          3.73355858e-02, -4.18290347e-02, -2.96806321e-02,
         -2.68692851e-01,  1.87746614e-01, -6.29172176e-02,
         -9.65826735e-02, -1.58448145e-01, -9.83048081e-02,
         -1.15332507e-01, -2.52439708e-01, -1.64923090e-02,
         -1.82154953e-01,  3.03539842e-01, -1.27920032e-01,
         -2.91740913e-02, -7.13997483e-02, -9.68693104e-03,
         -2.15688646e-01,  1.76973924e-01,  3.58888879e-02,
          2.58858263e-01,  7.00520910e-03, -1.69669151e-01,
          2.45955199e-01,  2.95303524e-01,  2.28900194e-01,
          2.84228418e-02,  4.99131233e-02,  3.53919305e-02,
          3.09223798e-03, -6.76970333e-02,  1.87969759e-01,
         -7.95611516e-02,  9.74717885e-02,  4.65356223e-02,
         -1.64031595e-01, -8.82140324e-02, -2.05547899e-01,
          1.24132503e-02,  4.04064208e-02,  9.81563106e-02,
         -7.51189142e-02,  1.91976264e-01, -2.50936717e-01,
          2.42955655e-01,  1.25532150e-01, -1.57916591e-01,
         -7.12718293e-02,  3.22834462e-01, -2.63849795e-02,
         -3.16729881e-02, -6.16177768e-02,  7.77762607e-02,
         -3.33179772e-01,  1.67842790e-01, -3.34945619e-01,
          5.09662069e-02, -1.31736621e-01,  5.37067093e-02,
         -2.32448757e-01,  6.61823750e-02, -4.40920293e-02,
          1.92122504e-01, -2.65778393e-01,  3.19572479e-01,
         -5.25953770e-02,  1.47018805e-01,  1.24681279e-01,
          5.89878205e-03, -1.25903636e-01, -6.18327335e-02,
         -2.68951833e-01, -1.88242972e-01,  3.16535262e-03,
         -1.56833470e-01, -1.18356347e-01, -2.13378623e-01,
         -1.85134619e-01, -9.01672989e-02, -2.90734261e-01,
         -1.27659708e-01,  7.06327483e-02,  4.95170355e-02,
         -1.69987187e-01,  1.19172363e-02,  1.64006650e-01,
          2.87751388e-02,  1.74496561e-01,  7.85352662e-02,
         -1.56058418e-02, -6.60010129e-02, -1.75097734e-01,
         -9.27310251e-03,  7.00050518e-02, -3.54707867e-01,
         -1.33320782e-02,  9.04903635e-02, -1.80789530e-01,
          6.27044067e-02,  1.04739787e-02,  6.44926429e-02,
         -2.48391137e-01, -2.63030138e-02,  1.02879189e-01,
          3.53213623e-02,  1.07495554e-01, -9.39566642e-02,
          1.22008517e-01,  3.00089777e-01,  2.13514030e-01,
          1.37124555e-02, -2.63180405e-01, -1.12641439e-01,
         -1.35698631e-01,  1.04226530e-01, -1.69520482e-01,
          2.67150760e-01,  5.44129238e-02,  1.63907081e-01,
         -7.85543174e-02,  2.31561020e-01, -3.79006341e-02,
          7.72984922e-02, -1.38678521e-01,  1.80689707e-01,
         -1.48060381e-01, -9.15954262e-02,  3.48635644e-01,
          2.18871653e-01, -6.84766844e-02, -2.01111659e-01,
         -3.61464351e-01,  1.65099695e-01, -1.57670528e-02,
         -2.28678714e-02,  4.81116511e-02, -9.35604647e-02,
          7.37490505e-02,  2.77552992e-01, -1.72774479e-01,
         -1.66049376e-01,  8.92852321e-02, -1.42109051e-01,
          2.28552297e-01,  2.39247009e-01,  2.55364664e-02,
          1.75254688e-01,  7.04279840e-02, -4.32433859e-02,
         -1.64309382e-01, -1.12742245e-01, -3.27128530e-01,
          8.54558274e-02,  1.55690432e-01, -1.20175950e-01,
          1.53440922e-01,  5.81078529e-02,  9.30526480e-02,
          1.51178420e-01, -9.16022733e-02, -8.03520083e-02,
          1.61639620e-02,  9.85776633e-02,  1.73375964e-01,
         -7.47957528e-02, -1.63081028e-02,  1.87693864e-01,
          1.31293178e-01, -1.54614583e-01, -1.35160789e-01,
          1.42213836e-01,  2.57220894e-01,  3.15345265e-02,
         -2.53422499e-01,  1.58247173e-01, -1.07763611e-01,
         -4.61557396e-02,  1.75293356e-01,  1.33772874e-02,
         -1.29156470e-01, -4.60151630e-03,  1.46810085e-01,
         -1.14266224e-01,  2.84898937e-01,  3.11792549e-02,
         -1.94118515e-01, -1.50354043e-01,  3.89389247e-02,
          9.45441201e-02,  9.59283207e-03,  3.50911826e-01,
          1.08925059e-01, -1.36936411e-01,  1.84643432e-01,
         -1.27959568e-02, -1.50724337e-01,  1.50949046e-01,
          4.21927050e-02, -9.38108936e-02, -2.72721291e-01,
         -4.71560359e-01,  4.73034717e-02,  1.74125489e-02,
          3.01429689e-01, -1.59585357e-01,  3.69751453e-01,
         -1.91232353e-01,  5.68885691e-02, -8.08726102e-02,
         -3.08598489e-01, -1.36133775e-01,  2.37465590e-01,
          8.48359019e-02,  1.82774857e-01, -3.04479599e-01,
         -6.00757338e-02,  1.88703761e-02,  1.93009935e-02,
         -5.26634812e-01, -3.99783347e-03,  1.26440018e-01,
         -3.97916317e-01, -4.24087606e-02,  9.06116366e-02,
         -7.98350051e-02,  4.04750668e-02, -1.40972540e-01,
         -2.62471825e-01, -2.22899854e-01, -1.28324583e-01,
          4.44906950e-02, -2.36324534e-01,  3.12211454e-01,
          5.65139316e-02, -2.02097222e-02, -8.24595764e-02,
         -4.38563414e-02,  2.18486756e-01, -2.44038031e-01,
         -1.36417355e-02, -8.35780650e-02,  6.02442911e-03,
         -1.11236475e-01, -6.10945038e-02,  4.00343835e-01,
         -3.88591625e-02,  1.65084630e-01,  1.56718165e-01,
         -3.81212205e-01, -5.65622598e-02, -1.47422239e-01,
          9.78586376e-02,  4.83868159e-02,  2.19306096e-01,
         -1.36258483e-01,  3.35672311e-03, -1.88873842e-01,
         -7.45270327e-02, -2.24406701e-02,  1.22653633e-01,
         -1.69151992e-01,  2.39635482e-02,  1.28384707e-02,
          6.70220051e-03,  1.19020045e-01, -2.75987267e-01,
          2.01498792e-01,  9.78373513e-02, -1.00165457e-01,
          4.77215350e-02,  1.84190482e-01,  1.83723584e-01,
         -7.53486976e-02, -3.94322164e-02, -2.07454711e-01,
         -1.25981018e-01,  9.25583486e-03, -1.28988951e-01,
          8.23419765e-02, -4.18408699e-02,  5.24739213e-02,
          1.91066042e-01,  2.95291752e-01,  4.69869524e-02,
         -1.47945568e-01, -4.63601798e-02,  1.81392636e-02,
         -4.67444547e-02,  1.54415712e-01,  2.49928162e-01,
          1.22992292e-01,  2.95041911e-02,  1.13029659e-01,
          2.89018989e-01,  5.55683337e-02, -9.45250690e-02,
         -8.78248513e-02,  1.72285922e-02, -1.09216630e-01,
         -1.27950996e-01, -1.42274410e-01,  1.78940266e-01,
         -2.71728277e-01, -3.97734851e-01, -5.74070252e-02,
         -6.58618659e-02, -2.02899337e-01, -1.12783990e-03,
          1.25017598e-01, -6.08653277e-02,  9.98467878e-02,
         -6.91055954e-02, -1.63219944e-01,  6.82123303e-02,
          5.59724011e-02,  6.22985512e-02, -1.90589100e-01,
         -2.39380434e-01, -3.23818892e-01, -1.93620473e-01,
          1.33325741e-01, -2.30274588e-01, -1.58297256e-01,
          4.18204777e-02,  1.02159768e-01,  8.21326673e-02]]),
 'documents': None,
 'uris': None,
 'included': ['embeddings'],
 'data': None,
 'metadatas': None}